# Generated by Django 3.0.5 on 2020-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('User_Id', models.CharField(auto_created=True, max_length=15)),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Date_of_Birth', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=6)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Phone_Number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('Security_Question', models.CharField(max_length=50)),
                ('Security_Answer', models.CharField(max_length=50)),
                ('UserType', models.CharField(default='Admin', max_length=20)),
                ('User_Image', models.ImageField(default='adminzone/mUser.png', upload_to='adminzone/Admin_Images')),
                ('Cart_Item', models.TextField()),
                ('Balance', models.CharField(default=0, max_length=7)),
                ('Date_of_Register', models.CharField(default='19/08/2020', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Item_id', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=70)),
                ('Author', models.CharField(default='Ewebgo', max_length=50)),
                ('Type', models.CharField(default='Item', max_length=20)),
                ('Item_type', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=12)),
                ('Quantity', models.CharField(max_length=6)),
                ('Sellars_Name', models.TextField()),
                ('Sellars_Shop_Address', models.TextField()),
                ('Post_Date', models.CharField(default='19/08/2020', max_length=30)),
                ('Item_Image', models.ImageField(default='adminzone/Product_Images/fav.png', upload_to='adminzone/Product_Images')),
                ('Extra_Images1', models.ImageField(default='adminzone/Product_Images/fav.png', upload_to='adminzone/Product_Images')),
                ('Extra_Images2', models.ImageField(default='adminzone/Product_Images/fav.png', upload_to='adminzone/Product_Images')),
                ('Descriptions', models.TextField()),
                ('Specifications', models.TextField()),
                ('Updater_Admin_Id', models.CharField(max_length=100)),
            ],
        ),
    ]
