# Generated by Django 3.0.5 on 2020-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=15)),
                ('Product_id', models.CharField(max_length=15)),
                ('Product_Name', models.CharField(max_length=35)),
                ('Product_Price', models.CharField(max_length=10)),
                ('Product_Quantity', models.CharField(max_length=5)),
                ('Product_Details', models.TextField()),
                ('Product_Add_Date', models.CharField(default='19/08/2020', max_length=30)),
                ('Product_Seller', models.CharField(max_length=50)),
                ('Product_image', models.ImageField(default='userzone/Cart/ProductImages/fav.png', upload_to='userzone/Cart/ProductImages')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.CharField(max_length=20)),
                ('Product_Name', models.CharField(max_length=35)),
                ('Product_Price', models.CharField(max_length=10)),
                ('Product_Quantity', models.CharField(max_length=5)),
                ('Product_Details', models.TextField()),
                ('Product_Seller', models.CharField(max_length=50)),
                ('Product_Order_Date', models.CharField(default='19/08/2020', max_length=30)),
                ('User_Name', models.CharField(max_length=50)),
                ('User_Email', models.EmailField(max_length=254)),
                ('User_Address', models.TextField()),
                ('Tracking_Address', models.CharField(default='EwebgoStore', max_length=70)),
                ('User_Number', models.CharField(max_length=15)),
                ('Payment_Status', models.CharField(max_length=25)),
            ],
        ),
    ]
