# Generated by Django 3.0.5 on 2020-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('User_Id', models.CharField(auto_created=True, max_length=15)),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Date_of_Birth', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=6)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Phone_Number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('Security_Question', models.CharField(max_length=50)),
                ('Security_Answer', models.CharField(max_length=50)),
                ('UserType', models.CharField(default='User', max_length=20)),
                ('User_Image', models.ImageField(default='userzone/mUser.png', upload_to='userzone/User_Images')),
                ('Cart_Item', models.TextField()),
                ('Balance', models.CharField(default=0, max_length=7)),
                ('Date_of_Register', models.CharField(default='19/08/2020', max_length=30)),
            ],
        ),
    ]
